### ISSUE TITLE
Thermal Innovation bore and magnet upgrades cannot be crafted

### ISSUE THREAD

**Issue by Post-opKen** [CoFH/cofh.github.io#51]
The bore and magnet are uncraftable beyond their basic versions. The recipes for the basic bore and the basic magnet work fine, but the hardened and above versions wont craft. I noticed the infuser recipes are fine, so I wonder if the problem could have to do with energy storage in the crafting components in the upgraded recipes?

The components of the basic versions do not store energy, but since the upgraded versions of the bore and magnet require the previous version of the item, it may be having trouble with the energy storage information. Just a hunch :/

**Comment by KingLemming** [comment]
First of all, wrong repo.

I can't make this happen, but I think I know what the issue may be. Will have a hotfix shortly.
