### ISSUE TITLE
Thermal Expansion crashing game on start up

### ISSUE THREAD

**Issue by twincitygamer** [CoFH/cofh.github.io#74]
link to error
https://gyazo.com/1ce0caafb5ae5546ccb0d3b39b295390
copy of the error 
"The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V"

pastebin for crash report 
pastebin.com/Axc45m3u

**Comment by Griffdith** [comment]
Your supposed to send these in the [Feedback](https://github.com/CoFH/Feedback/issues/new) repo

**Comment by KingLemming** [comment]
Wrong repo. And the cause is BaseMetals. Disable Thermal Expansion compat.
