### ISSUE TITLE
Augment crafttweaker api

### ISSUE THREAD

**Issue by EthernalVoid** [CoFH/cofh.github.io#82]
Can you add the api for crafttweaker to be able to specify augment-only recipes:

eg. Additional ores to be able to be added to pulveriser processing with liquid petrotheum or the induction smelter pyrotheum augmented machines.

THAT would be great :D

**Comment by KingLemming** [comment]
Not possible without a massive rewrite, so not happening.

Crafttweaker support is incidental; we have our own custom content format and in the future that'll be the way to go
